name: email_test

on:
  workflow_dispatch:
    inputs:
      subject:
        default: 'Message From Github Actions.'
        required: true
        type: string
  workflow_call:
    inputs:
      subject:
        default: 'Message From Github Actions.'
        required: true
        type: string

jobs:
  email_test:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v4
       
       - name: Send mail
         uses: dawidd6/action-send-mail@v4
         with:
           server_address: smtp.163.com
           server_port: 465
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: ${{ inputs.subject }}
           body: Github Action!
           to: ${{ secrets.PRIVATE_EMAIL_ADDRESS }}
           from: GitHub Actions
           # content_type: text/html
