name: gdrive_test
on:
  workflow_dispatch:

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: outputs.txt
          # name: documentation.zip
          folderId: ${{ secrets.GDRIVE_FOLDERID }}
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          encoded: false
